<a href="https://colab.research.google.com/github/Dhanu1402/python_with_ml/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - numerical python

Advantages of numpy arrays :-  
1. Allows several mathematical operations
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time taken

In [2]:
from time import process_time

Time taken by list

In [5]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i + 5 for i in python_list]
end_time = process_time()
print(end_time - start_time) # ans will be in seconds

0.0006477589999995814


In [6]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5 
end_time = process_time()
print(end_time - start_time) # ans will be in seconds

0.0017875849999997584


Numpy Arrays

In [8]:
#list
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [9]:
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [10]:
# creating 1d array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a.shape # through thos commad can find rows and columns of a array

(4,)

In [15]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
b.shape

(2, 4)

In [17]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays

In [20]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# array of particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [26]:
# creating an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.73596697 0.68084044 0.07611487 0.44358179]
 [0.72188836 0.12145703 0.7424287  0.36076741]
 [0.02421948 0.69817007 0.42571057 0.03300797]]


In [32]:
# random integer value array
c = np.random.randint(10, 100, (3,5))
print(c)

[[43 98 49 47 42]
 [63 13 11 85 87]
 [99 47 63 58 32]]


In [34]:
# array of evenly spaced values
d = np.linspace(10, 30, 5) # 10 is starting value 30 is end value and 5 is the number of elements we want to print
print(d)

[10. 15. 20. 25. 30.]


In [37]:
# array of even spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [38]:
# convert a list ot numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [39]:
c = np.random.randint(10,90,(5,5))
print(c)

[[79 20 57 39 15]
 [35 62 64 38 23]
 [35 56 23 47 81]
 [46 29 10 36 78]
 [66 25 48 36 46]]


In [40]:
# array dimension
print(c.shape)

(5, 5)


In [41]:
#number of dimensions
print(c.ndim)

2


In [42]:
# number of elements in an array
print(c.size)

25


In [43]:
# checking data type of values in array
print(c.dtype)

int64


Mathematical operations on a np array

In [44]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # here + whill concatenate the 2 lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [45]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 1 2]
 [6 4 2]
 [3 0 6]]
[[16 19 15]
 [11 16 13]
 [15 14 19]]


In [47]:
print(a+b) # here + will be performing element wise addition

[[21 20 17]
 [17 20 15]
 [18 14 25]]


In [48]:
print(a-b)
print(a*b)
print(a/b)

[[-11 -18 -13]
 [ -5 -12 -11]
 [-12 -14 -13]]
[[ 80  19  30]
 [ 66  64  26]
 [ 45   0 114]]
[[0.3125     0.05263158 0.13333333]
 [0.54545455 0.25       0.15384615]
 [0.2        0.         0.31578947]]


In [50]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 7 1]
 [6 6 2]
 [0 0 4]]
[[16 19 15]
 [17 15 19]
 [15 18 17]]


In [51]:
print(np.add(a,b))

[[21 26 16]
 [23 21 21]
 [15 18 21]]


In [52]:
print(np.subtract(a,b))

[[-11 -12 -14]
 [-11  -9 -17]
 [-15 -18 -13]]


In [53]:
print(np.multiply(a,b))

[[ 80 133  15]
 [102  90  38]
 [  0   0  68]]


In [54]:
print(np.divide(a,b))

[[0.3125     0.36842105 0.06666667]
 [0.35294118 0.4        0.10526316]
 [0.         0.         0.23529412]]


Array Manipulation

In [55]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[9 1 1]
 [7 9 1]]
(2, 3)


In [56]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 7]
 [1 9]
 [1 1]]
(3, 2)


In [57]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[7 0 3]
 [4 2 4]]
(2, 3)


In [58]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 4]
 [0 2]
 [3 4]]
(3, 2)


In [59]:
# reshaping a array
a = np.random.randint(0,10, (2,3))
print(a)
print(a.shape)


[[1 3 0]
 [2 4 8]]
(2, 3)


In [61]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 3]
 [0 2]
 [4 8]]
(3, 2)
